name: Code safe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  codesafe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Ruff linting with fix
        run: |
          poetry run ruff check --fix .

      - name: Check Ruff formatting
        run: |
          poetry run ruff format --check .

      - name: Audit dependencies
        run: |
          poetry run pip-audit

      - name: Run Mypy type checking
        run: |
          poetry run mypy . --strict --show-error-codes --exclude migrations --exclude tests
